# Generated by Django 5.2.17 on 2026-08-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending Verification'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', help_text="Only Confirmed payments count towards a student's paid fees.", max_length=10),
        ),
    ]
