# Generated by Django 5.2.17 on 2026-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('ADMISSION', 'Admission Fee'), ('EXAM', 'Exam Fee')], max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fee_type',
            field=models.CharField(choices=[('ADMISSION', 'Admission Fee'), ('EXAM', 'Exam Fee')], default='ADMISSION', max_length=15),
        ),
    ]
