# Generated by Django 5.2.17 on 2026-08-06 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('DEPT_ADMIN', 'Department Administrator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('LIBRARIAN', 'Librarian'), ('CASHIER', 'Cashier')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='DepartmentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_at', models.DateField(auto_now_add=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='administrator', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dept_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Administrator',
                'ordering': ['department__code'],
            },
        ),
    ]
