# Generated by Django 5.2.17 on 2026-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_assessment_coursematerial_assessmentmark_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoursemark',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='incoursemark',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='incoursemark',
            name='quiz',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('THEORY', 'Theory Course'), ('LAB', 'Lab Course')], default='THEORY', max_length=10),
        ),
        migrations.AddField(
            model_name='incoursemark',
            name='attendance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='incoursemark',
            name='term_test',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('TT', 'Term Test'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('LAB', 'Lab Work'), ('VIVA', 'Viva')], max_length=15),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(default='', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade_point',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
    ]
